# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-18 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import my_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('maximum_students', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('student_identification', models.CharField(default=my_app.models.getUniqueString, max_length=20, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='my_app.School')),
            ],
        ),
    ]
