# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-16 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('maximum_students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('student_identification', models.CharField(max_length=20)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.School')),
            ],
        ),
    ]
