# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-16 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='school_id',
            new_name='school',
        ),
        migrations.AlterField(
            model_name='school',
            name='maximum_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_identification',
            field=models.CharField(default=b'923914eb-90da-43be-b', max_length=20, unique=True),
        ),
    ]
